### ISSUE TITLE
What error?, i can't run launcher.py

### ISSUE THREAD

**Issue by AxeyedTran** [RealistikDash/PyMyMC#1]
![image](https://user-images.githubusercontent.com/86827070/165069968-09a0b5a5-e50d-4c22-816b-e117ad365509.png)

**Comment by RealistikDash** [comment]
Does your VM have a working internet connection that is able to access minecraft.net? Other than that I could possibly imagine Minecraft changing some of the API stuff. I'll investigate this issue soon

**Comment by AxeyedTran** [comment]
virtual machine i have connection to internet but i think minecraft changed the api or the code is error

**Comment by RealistikDash** [comment]
Okay I am able to replicate this issue, will commit a fix soon

**Comment by RealistikDash** [comment]
The commit above should solve this issue.
