### ISSUE TITLE
luncher not working

### ISSUE THREAD

**Issue by marhau-dev** [RealistikDash/PyMyMC#5]
E:\python-projects\pythonProject\launcher.py 
Traceback (most recent call last):
  File "E:\python-projects\pythonProject\launcher.py", line 33, in <module>
    from _typing import (
ImportError: cannot import name 'MinecraftRelease' from '_typing' (unknown location)

**Comment by RealistikDash** [comment]
Make sure you are in the same directory as the launcher.py file when starting it

**Comment by RealistikDash** [comment]
Fixed, turned out to be a weird issue.
